Dynamic page title based on error kind
duckduckgo/content-scope-scripts pull request #1034
Opened 2024-09-12 13:28 UTC by mgurgel

Asana: https://app.asana.com/0/1206594217596623/1208270234071170/f

- Sets the page title to match translated heading for that kind of error, e.g.
    - Phishing: "Warning: This site puts your personal information at risk"
    - SSL error: "Warning: This site may be insecure"

## Testing

- Run the macOS app with this branch of C-S-S
- Follow the steps to reproduce in the Asana task
- Verify that the page title in the back button popover matches the kind of error

2024-09-12 20:10 UTC, shakyShane requested changes

2024-09-12 20:10 UTC, shakyShane commented on packages/special-pages/pages/special-error/app/components/App.jsx
> +    }, [])
```suggestion
    useEffect(() => {
        switch(kind) {
            case 'phishing':
                document.title = t('phishingPageHeading')
                break;
            default:
                document.title = t('sslPageHeading')
        }
    }, [kind, t])
```

2024-09-13 09:21 UTC, mgurgel commented on packages/special-pages/pages/special-error/app/components/App.jsx
> +    }, [])
Of course!! Thanks

2024-10-10 12:55 UTC, not-a-rootkit commented
Sorry I'm only just getting to this now - I've tested this fix and I think it properly addresses this bug: https://app.asana.com/0/1204023833050360/1208270234071170/f. Are we in a position to rebase and merge this?

2024-10-10 13:22 UTC, shakyShane approved these changes

2024-10-10 13:24 UTC, merged