[WIP] Onboarding Highlights
duckduckgo/content-scope-scripts pull request #1059
Opened 2024-09-16 14:40 UTC by mgurgel

Asana: https://app.asana.com/0/1206594217596623/1208204606544051/f

- Updated onboarding steps to match Figma
- Implemented Dax speech bubble design
- Added browser comparison table to Windows and macOS
- General UI updates on light and dark modes
 
### In progress
- Restyling/adapting UI components (progress bar, buttons, etc)
- "Set as default" success state
- Add to dock/taskbar step

### Todo
- "Migrate your stuff" step
- Duck Player step
- Customization step
- All animations and step transitions
- UI differences between macOS and Windows (button order, messaging, copy)

2024-09-25 09:51 UTC, mgurgel commented on packages/special-pages/pages/onboarding/app/settings.js
> +    withPlatformName (name) {
Setting up for future implementation of platformName

2024-10-28 09:30 UTC, shakyShane requested changes

2024-10-28 09:30 UTC, shakyShane commented on special-pages/pages/onboarding/app/components/Typed.js
> +            // TODO: Check that it's not affecting v1/v2
remove this if you've verified it - just to be clear it's no-longer an issue.

2024-10-28 09:30 UTC, shakyShane commented on special-pages/pages/onboarding/app/global.js
> +    console.groupEnd()
let's remove these again to prevent logging noise in prod?

2024-10-28 09:58 UTC, shakyShane approved these changes
Tested extensively for weeks with different teams. 

I also validated that this new work does not impact the existing flows on windows (v1+v2)

2024-10-28 10:08 UTC, merged