Replace FLOC with browsingTopics
duckduckgo/content-scope-scripts pull request #17
Opened 2022-01-27 00:18 UTC by SlayterDev

https://app.asana.com/0/1163321984198618/1201719300245228/f

`browsingTopics` is effectively replacing `floc`. This PR turns our `floc` protection into a `browsingTopics` protection.

New to this build process. Hopefully this looks right.

2022-04-14 01:56 UTC, jonathanKingston requested changes
I think we're missing a few APIs here.

2022-04-14 01:56 UTC, jonathanKingston commented on src/features/google-rejected.js
> +    if ('browsingTopics' in Document.prototype) {
If we make the if statement inside the try, we don't need to do 3 of them aka:

```
try {
    if ('browsingTopics' in Document.prototype) {
        ....
    }
    if (...) {
        ...
    }
} catch {
    // Throw away this exception, it's likely a confict with another extension
}
```

2022-04-14 01:56 UTC, jonathanKingston commented on src/features/google-rejected.js
> +            delete Navigator.prototype.joinAdInterestGroup
I think there's some more here https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/ad_auction/navigator_auction.idl:

```
  [CallWith=ScriptState, Measure, RaisesException]
  void joinAdInterestGroup(AuctionAdInterestGroup group, double durationSeconds);

  [CallWith=ScriptState, Measure, RaisesException]
  void leaveAdInterestGroup(optional AuctionAdInterestGroup group);

  [CallWith=ScriptState, Measure, RaisesException]
  void updateAdInterestGroups();

  [RuntimeEnabled=Fledge, CallWith=ScriptState, Measure, RaisesException]
  Promise<USVString?> runAdAuction(AuctionAdConfig config);

  [RuntimeEnabled=Fledge, CallWith=ScriptState, Measure, RaisesException]
  sequence<USVString> adAuctionComponents([Clamp] unsigned short numComponents);

```

2022-04-14 22:29 UTC, jonathanKingston approved these changes

2022-04-14 22:30 UTC, merged

2024-12-20 01:42 UTC, Pitpul1 reviewed
Wel whel