MV3 click to load support
duckduckgo/content-scope-scripts pull request #189
Opened 2022-11-14 08:10 UTC by ladamski

https://app.asana.com/0/72649045549333/1202839073279061/f

2022-11-28 05:02 UTC, ladamski commented
@jonathanKingston would appreciate a pass on this, should be complete but still working through some feedback on ddg2dnr and extension PRs so there's some chance this might change (a bit).

2022-12-05 18:04 UTC, jonathanKingston commented on inject/chrome.js
> +            const stringifiedArgs = JSON.stringify({ detail: msg })
Also doesn't this break the cookie update messages also?

2022-12-05 18:21 UTC, jonathanKingston requested changes
Unless I'm misunderstanding the code I think there's cookie and Firefox issues here.

2022-12-06 04:03 UTC, ladamski commented on inject/chrome.js
> +            const stringifiedArgs = JSON.stringify({ detail: msg })
Thanks good catch!  I had test this earlier but then broke it with subsequent updates.  Now fixed again.  

I tested the content scope script cookie updates in MV2/MV3/FF (via console spam) and it still works; they don't go through this proxy AFAICT.

```
diff --git a/src/features/cookie.js b/src/features/cookie.js
index 73954cc..1848085 100644
--- a/src/features/cookie.js
+++ b/src/features/cookie.js
@@ -188,6 +188,7 @@ export function init (args) {
 }

 export function update (args) {
+    console.warn('cookie update', args && args.trackerDefinition && args.hostname)
     if (args.trackerDefinition) {
         trackerHosts.add(args.hostname)
     }
```

2022-12-06 16:41 UTC, jonathanKingston approved these changes

2022-12-06 16:41 UTC, jonathanKingston commented
To merge you'll have to rebuild the inject file for chrome.

2022-12-06 17:19 UTC, jonathanKingston approved these changes

2022-12-06 17:19 UTC, merged