[WIP] Extract Apple Config processing functions
duckduckgo/content-scope-scripts pull request #20
Opened 2022-02-02 15:57 UTC by SlayterDev

https://app.asana.com/0/72649045549333/1201640241287329/f

2022-02-08 17:53 UTC, jonathanKingston requested changes
Looks fine to me, one function to be removed.

Did you check the generated output of Chrome and Firefox, happy to check them over just a little nervous without some manual verification.

2022-02-08 17:53 UTC, jonathanKingston commented on scripts/inject.mjs
> +async function initApple() {
This function can be removed now it seems.

2022-02-08 17:56 UTC, SlayterDev commented
@jonathanKingston It seems with the rollup it moves everything in those files to an anonymous function where there used to be some parts at the top level. Also some indentation is added. There shouldn't be any change to functionality but feel free to take a peak if you like.

2022-02-17 17:43 UTC, jonathanKingston commented
As some files have changed here in the repo are you able to rebase and rebuild? We're good to merge then.

2022-02-17 18:07 UTC, jonathanKingston approved these changes

2022-02-17 18:08 UTC, merged