macos duckplayer
duckduckgo/content-scope-scripts pull request #459
Opened 2023-04-22 17:58 UTC by shakyShane

2023-04-22 17:58 UTC, shakyShane commented
Current dependencies on/for this PR:
* main
  * **PR #458** <a href="https://app.graphite.dev/github/pr/duckduckgo/content-scope-scripts/458" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #459** <a href="https://app.graphite.dev/github/pr/duckduckgo/content-scope-scripts/459" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/content-scope-scripts/459?utm_source=stack-comment).

2023-04-23 19:53 UTC, jonathanKingston commented on package-lock.json
> +    "node_modules/ansi-colors": {
How come this changed?

2023-04-23 19:58 UTC, jonathanKingston commented on inject/apple.js
> +    json.features.duckPlayer = {
Remove please

2023-04-23 20:00 UTC, jonathanKingston commented on packages/messaging/lib/webkit.js
> +        Error: window.Error,
Why is this platform specific?

Can we move it somewhere else?

2023-04-23 20:06 UTC, jonathanKingston commented on src/features/duck-player.js
> +            const context = new MessagingContext({
Can you construct this outside the if statement and share it with the Windows code above?

2023-04-23 20:07 UTC, jonathanKingston commented on packages/special-pages/index.mjs
> +    console.log('INLINE:', relative(ROOT, inlineJob.src))
Remove?

2023-04-23 20:08 UTC, jonathanKingston commented on packages/messaging/lib/webkit.js
> +    async request (msg, _opts) {
Remove opts?

2023-04-23 20:08 UTC, jonathanKingston requested changes
Some minor changes needed :)

Thanks

2023-04-23 20:13 UTC, jonathanKingston commented on packages/messaging/lib/webkit.js
> +        Error: window.Error,
Ignore it's webkit only. We probably don't want it to be eventually; surely windows needs it?

2023-04-23 20:19 UTC, shakyShane commented
Sorry should have marked as draft, not quite ready for review - although the points raised are still valid, thanks :)

2023-06-10 18:14 UTC, jonathanKingston commented on src/create-messaging.js
> +    const context = new MessagingContext({
This will need to be refactored when Frans code lands, can you file a follow up issue to track?

2023-06-10 18:15 UTC, jonathanKingston commented on packages/special-pages/playwright.config.js
> +    fullyParallel: true,
Turn off for CI?

2023-06-10 18:22 UTC, jonathanKingston commented on src/features/duckplayer/util.js
> +    callbacks = []
Can we call this `loadedCallbacks` to disambiguate?

2023-06-10 18:28 UTC, jonathanKingston commented on src/type-helpers.mjs
> +import { readFileSync } from 'node:fs'
This belongs in the test directory.

2023-06-10 18:30 UTC, jonathanKingston commented on packages/special-pages/tests/page-objects/mocks.js
> +        if (this.platform.name === 'windows') {
Can we use this.build.switch here?

2023-06-10 18:34 UTC, jonathanKingston commented on packages/special-pages/pages/duckplayer/src/js/index.js
> +        if (opts.injectName === 'windows') {
Should all this messaging be out into it's own getter like Fran did?

2023-06-10 18:38 UTC, jonathanKingston commented on packages/special-pages/tests/page-objects/duck-player.js
> +        case 'windows': {
Can we use build.switch here also?

2023-06-10 18:39 UTC, jonathanKingston commented on packages/special-pages/index.mjs
> +    console.log('INLINE:', relative(ROOT, inlineJob.src))
Can we remove this comment? (or at least make it debug only?)

2023-06-10 18:41 UTC, jonathanKingston reviewed
Few comments and then should be good to go

2023-06-10 19:11 UTC, shakyShane commented
@jonathanKingston - should be everything addressed now - I'll create a follow-up task in asana to review messaging construction once both mine + @franfaccin 's PRs have landed

2023-06-12 11:53 UTC, jonathanKingston approved these changes
LGTM

2023-06-12 15:11 UTC, merged